Foregate.Redrow/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
//
using Foregate.Redrow.Models;
using Foregate.Redrow.Helpers;
using Foregate.Redrow.Properties;
//
namespace Foregate.Redrow.Controllers
{
    [HandleError]
    [ValidateOnlyIncomingValues]
    public class ImageController : Controller
    {
        RedrowDataContext RDC = new RedrowDataContext();
        
        /// <summary>
        /// Import CSV file of images and stuff
        /// </summary>
        /// 
        //[Authorize]
        //public ActionResult Convert()
        //{
        //    @ViewBag.Title = "Image convert";
        //    CatalogListViewData viewData = new CatalogListViewData();
        //    List<FileInfo> files = new System.IO.DirectoryInfo(Path.Combine(Properties.Settings.Default.ThumbsAndPreviewsFolder, "Preview")).GetFiles("*.png", SearchOption.TopDirectoryOnly).OrderByDescending(p => p.CreationTime).ToList();
        //    string path = Path.Combine(Properties.Settings.Default.ThumbsAndPreviewsFolder, "Convert");
        //    viewData.files = new List<FileInfo>();
        //    foreach (FileInfo file in files)
        //    {
        //        string fileName = Path.GetFileName(file.FullName);

        //        if (!System.IO.File.Exists(Path.Combine(path, fileName)))
        //        {
        //            viewData.files.Add(file);
        //        }
        //    }

        //    System.IO.File.AppendAllText(Server.MapPath("~/App_Data/") + "ConvertErrors.log", "\r\n Number of files to convert : " + viewData.files.Count());

        //    viewData.Upload = System.IO.File.ReadAllText(Server.MapPath("~/App_Data/") + "ConvertErrors.log");
        //    viewData.RecordCount = viewData.files.Count();
        //    return View(viewData);
        //}
        //[Authorize, HttpPost]
        //public ActionResult Convert(FormCollection model)
        //{
        //    ImageImport ii = new ImageImport();
        //    ii.RootFolder = Server.MapPath("~/App_Data/");
        //    ii.Log = "ConvertErrors.log";
        //    ii.DirectoryToImport = new System.IO.DirectoryInfo(Path.Combine( Properties.Settings.Default.ThumbsAndPreviewsFolder,"Preview"));
        //    HttpContext.Application["ImageImport"] = ii;

        //    var taskId = Guid.NewGuid();
        //    tasks.Add(taskId, "Processed " + ii.FilesProcessed + " of " + ii.TotalFiles + ". Converted " + ii.AddedCount + ". Working on file: " + ii.WorkingOn);

        //    List<FileInfo> allFiles = new System.IO.DirectoryInfo(Path.Combine(Properties.Settings.Default.ThumbsAndPreviewsFolder, "Preview")).GetFiles("*.png", SearchOption.TopDirectoryOnly).OrderByDescending(p => p.CreationTime).ToList();
        //    string path = Path.Combine(Properties.Settings.Default.ThumbsAndPreviewsFolder, "Convert");
        //    List<FileInfo> selectedFiles = new List<FileInfo>();
        //    foreach (FileInfo file in allFiles)
        //    {
        //        string fileName = Path.GetFileName(file.FullName);

        //        if (!System.IO.File.Exists(Path.Combine(path, fileName)))
        //        {
        //            selectedFiles.Add(file);
        //        }
        //    }
        //    ii.TotalFiles = selectedFiles.Count();
        //    ii.LogError("");
        //    ii.LogError("Started conversion of " + ii.TotalFiles + " files");
        //    Task.Factory.StartNew(() =>
        //    {
        //        foreach (FileInfo file in selectedFiles)
        //        {
        //            string fileName = Path.GetFileName(file.FullName);
        //            if (!System.IO.File.Exists(Path.Combine(path, fileName)))
        //            {
        //                ii.FilesProcessed++;
        //                if (!ii.ConvertFile(Path.Combine(Properties.Settings.Default.ThumbsAndPreviewsFolder, "Preview", fileName)))
        //                {
        //                    ii.LogError(fileName + " not converted");
        //                }
        //                else
        //                {
        //                    ii.LogError(fileName + " converted");
        //                    ii.AddedCount++;
        //                }

        //                tasks[taskId] = "Processed " + ii.FilesProcessed + " of " + ii.TotalFiles + ". Added " + ii.AddedCount + " and updated " + ii.UpdatedCount + ". Working on file: " + ii.WorkingOn;
        //                Thread.Sleep(2000);
        //            }
        //        }
        //        tasks.Remove(taskId);
        //    });
        //    return Json(taskId);
        //}
        //public ActionResult ConvertProgress(Guid id)
        //{
        //    return Json(tasks.Keys.Contains(id) ? tasks[id] : "");
        //}
        [Authorize]
        public ActionResult Delete(int id, string requestUrl)
        
        {

            Response.Write("Started");

            try
            {
                Image image = RDC.GetImage(id);
                // Check if imagedetail is in more than one category
                List<Image> images = RDC.GetImagesByImageDetail(image.ImageDetailId);


              

               
               

                List<BasketImage> BasketImages = RDC.GetBasketImageByImageId(id);
                foreach (BasketImage BI in BasketImages)
                {
                    RDC.BasketImages.DeleteOnSubmit(BI);
                    RDC.SubmitChanges();
                }



                RDC.Images.DeleteOnSubmit(image);
                RDC.SubmitChanges();

                //delete image from disk
                if (images.Count == 1)
                {


                    RDC.ImageDetails.DeleteOnSubmit(images[0].ImageDetail);
                    RDC.SubmitChanges();
                    image.DeleteFiles();
                }

               // RDC.ImageDetails.DeleteOnSubmit(image.ImageDetail);
                RDC.SubmitChanges();
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", new { error = ex.Message });
            }
            if (requestUrl == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return Redirect(requestUrl);
        }
        //[HttpPost, Authorize]
        //public ActionResult MoveImages(FormCollection model)
        //{
        //    //get checked images
        //    int ImageId;
        //    if (model["Process"] == "Move")
        //    {
        //        string srcFileName;
        //        if (int.Parse(model["SubCategoryId"]) != 0)
        //        {
        //            SubCategory MoveToSubCategory = RDC.GetSubCategory(int.Parse(model["SubCategoryId"]));
        //            foreach (string key in model.Keys)
        //            {
        //                //get checkbox
        //                if (key.StartsWith("chkSelect_"))
        //                {
        //                    if (model[key].StartsWith("true"))
        //                    {
        //                        ImageId = int.Parse(key.Substring(10));

        //                        //move these images
        //                        Image img = RDC.GetImage(ImageId);

        //                        if (img.SubCategoryId != MoveToSubCategory.SubCategoryId)
        //                        {
        //                            srcFileName = img.Location;

        //                            img.SubCategory = MoveToSubCategory;

        //                            RDC.SubmitChanges();

        //                            //move the physical file
        //                            if (System.IO.File.Exists(srcFileName))
        //                            {
        //                                //create the category folder if it doesn't exist
        //                                if (Directory.Exists(Path.GetDirectoryName(img.Location)) == false)
        //                                    Directory.CreateDirectory(Path.GetDirectoryName(img.Location));

        //                                System.IO.File.Move(srcFileName, img.Location);
        //                            }
        //                        }
        //                    }
        //                }
        //            }
        //            return RedirectToAction("List", "Images", new { id = MoveToSubCategory.SubCategoryId });
        //        }
        //        else
        //        {
        //            int MoveToCategoryId = int.Parse(model["CategoryId"]);
        //            Category MoveToCategory = RDC.GetCategory(MoveToCategoryId);

        //            foreach (string key in model.Keys)
        //            {
        //                //get checkbox
        //                if (key.StartsWith("chkSelect_"))
        //                {
        //                    if (model[key].StartsWith("true"))
        //                    {
        //                        ImageId = int.Parse(key.Substring(10));

        //                        //move these images
        //                        Image img = RDC.GetImage(ImageId);

        //                        if (img.CategoryId != MoveToCategoryId)
        //                        {
        //                            srcFileName = img.Location;

        //                            //img.Category = MoveToCategory;

        //                            RDC.SubmitChanges();
        //                            //move the physical file
        //                            if (System.IO.File.Exists(srcFileName))
        //                            {
        //                                //create the category folder if it doesn't exist
        //                                if (Directory.Exists(Path.GetDirectoryName(img.Location)) == false)

Foregate.Redrow/Controllers/ImageRotateController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace Foregate.Redrow.Controllers
{
    [Authorize]
    public class ImageRotateController : Controller
    {
        public ActionResult Rotate(int id, bool import = false)
        {
            using (var db = new Redrow.Models.RedrowDataContext())
            {
                var image = db.GetImage(id);
                if(image != null)
                {
                    int maxRetries = 5;
                    int currentRetry = 1;

                    while (currentRetry < maxRetries)
                    {
                        try
                        {
                            var path = "C:\\RedrowImages\\Preview\\" + image.ImageDetailId + ".png";
                            if (System.IO.File.Exists(path))
                            {
                                var imageObj = Image.FromFile(path);
                                var newImage =  RotateImage(imageObj, 90);
                                imageObj.Dispose();

                                System.IO.File.Delete(path);
                                newImage.Save(path);


                                //change convert image
                                var convertPath = "C:\\RedrowImages\\Convert\\" + image.ImageId + ".png";
                                var convertImage = Image.FromFile(convertPath);
                                var convertedImage = RotateImage(convertImage, 90);
                                convertImage.Dispose();

                                System.IO.File.Delete(convertPath);
                                convertedImage.Save(convertPath);

                                return Json(new { Success = true }, JsonRequestBehavior.AllowGet);
                            }
                            else
                            {
                                return Json(new { Error = "Unable to find requested image thumbnail. Path = " + path }, JsonRequestBehavior.AllowGet);
                            }
                        }
                        catch 
                        {
                            currentRetry += 1;
                            System.Threading.Thread.Sleep(500);
                        }
                    }

                    return Json(new { Error = "Unable to complete rotation due to an error, please contact an administrator." }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { Error = "Unable to find requested image." }, JsonRequestBehavior.AllowGet);
                }
            }
        }

        /// <summary>
        /// method to rotate an image either clockwise or counter-clockwise
        /// </summary>
        /// <param name="img">the image to be rotated</param>
        /// <param name="rotationAngle">the angle (in degrees).
        /// NOTE: 
        /// Positive values will rotate clockwise
        /// negative values will rotate counter-clockwise
        /// </param>
        /// <returns></returns>
        public Image RotateImage(Image img, float rotationAngle)
        {
            //create an empty Bitmap image
            Bitmap bmp = new Bitmap(img.Width, img.Height);

            //turn the Bitmap into a Graphics object
            Graphics gfx = Graphics.FromImage(bmp);

            //now we set the rotation point to the center of our image
            gfx.TranslateTransform((float)bmp.Width / 2, (float)bmp.Height / 2);

            //now rotate the image
            gfx.RotateTransform(rotationAngle);

            gfx.TranslateTransform(-(float)bmp.Width / 2, -(float)bmp.Height / 2);

            //set the InterpolationMode to HighQualityBicubic so to ensure a high
            //quality image once it is transformed to the specified size
            gfx.InterpolationMode = InterpolationMode.HighQualityBicubic;

            //now draw our new image onto the graphics object
            gfx.DrawImage(img, new Point(0, 0));

            //dispose of our Graphics object
            gfx.Dispose();

            //return the image
            return bmp;
        }
    }
}

Foregate.Redrow/Views/Image/Convert.cshtml
@model Foregate.Redrow.Models.CatalogListViewData
@{
    ViewBag.Title = "Convert";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@using Foregate.Redrow;
@using Foregate.Redrow.Helpers;
<script type="text/javascript">
    $(document).ready(function () {
        $('#Upload').scrollTop($('#Upload')[0].scrollHeight);
    });

    function updateMonitor(taskId, status) {
        $("#status").html(status);
    }

    $(function () {
        $("#load").click(function (e) {
            var url = '@Url.Action("Convert", "Image")';
            var urlp = '@Url.Action("ConvertProgress", "Image")';
            e.preventDefault();

            $.post(url, null, function (taskId) {

                // Init monitors
                $("#monitors").append($("<p id='status'/>"));
                updateMonitor(taskId, "Started");

                // Periodically update monitors
                var intervalId = setInterval(function () {
                    $.post(urlp, { id: taskId }, function (progress) {
                        if (progress == "") {
                            updateMonitor(taskId, "<b>Completed : </b>" + progress);
                            clearInterval(intervalId);
                            window.location.reload(true);
                        } else {
                            updateMonitor(taskId, progress);
                        }
                    });
                }, 100);
            });
        });
    });


</script>

@using (Html.BeginForm("Import", "Image", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div id="monitors"></div>
    <h3>You are about to convert the following files</h3>
  
    if (Model.files.Count() > 0)
    {
    <div>
        <ul>
            @foreach (FileInfo name in Model.files)
            { 
                <li>
                    @name
                </li>
            }
        </ul>
        <div style="float: right; padding-bottom: 20px;">
            <button onclick="JavascriptFunction();" type="submit" id="load">Upload</button>
        </div>
    </div>
    }
    else
    {
    @Html.Label("No files in the directory")
    }
    <div id="result">@Html.TextAreaFor(model => model.Upload, 14, 80, null)</div>
}

Foregate.Redrow/Views/Image/ImageDetail.cshtml
@model Foregate.Redrow.Models.ImagesViewData
@{
    Layout = "~/Views/Shared/_DetailLayout.cshtml";
}

@using Foregate.Redrow;
@using Foregate.Redrow.Helpers;
@using Foregate.Redrow.Models;

<script type="text/javascript">
    $.ajaxSetup({ cache: false });
    $(document).ready(function () {
        var EarningBasis = '@Html.Raw(Json.Encode(Model.Image.CategoryId))';
        switch (EarningBasis) {
            case "1":
                $("#CopyDiv, #CopyDiv input").hide().attr("disabled", "disabled");
                break;
        }
        $("#Category_CategoryId").change(function () {
            if ($(this).val() > 0) {
                $("#Image_SubCategoryId").empty();
                var urlemp = '@Url.Action("JsonSubCategory", "Category")';
                $.ajax({
                    url: urlemp,
                    cache: false,
                    data: { id: $(this).val() },
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        $.each(data, function (i, result) {
                            $("#Image_SubCategoryId").append("<option value='" + result.Value + "'>" + result.Text + "</option>");
                        });
                    },
                });
            }
        });
        $('#Image_Category_CatalogId').change(function () {
            $("#Category_CategoryId").empty();
            var urlemp = '@Url.Action("GetCategories", "Image")';
            $.ajax({
                type: 'GET',
                url: urlemp,
                cache: false,
                data: { id: $(this).val() },
                contentType: "application/json; charset=utf-8",
                success: function (returndata) {
                    $.each(returndata, function (i, result) {
                        $("#Category_CategoryId").append("<option value='" + result.Value + "'>" + result.Text + "</option>");
                    });
                },
            });
        });
        $("#CopyImage").change(function () {
            if (document.getElementById('CopyImage').checked) {
                $("#CopyDiv, #CopyDiv input").show().removeAttr("disabled");
                $("#MoveDiv, #MoveDiv input").hide().attr("disabled", "disabled");
            }
            else {
                $("#MoveDiv, #MoveDiv input").show().removeAttr("disabled");
            }
        });
        $("#MoveImage").change(function () {
            if (document.getElementById('MoveImage').checked) {
                $("#CopyDiv, #CopyDiv input").hide().attr("disabled", "disabled");
                $("#MoveDiv, #MoveDiv input").show().removeAttr("disabled");
                $('#copy').attr('checked', '');
            }
            else {
                $("#CopyDiv, #CopyDiv input").show().removeAttr("disabled");
            }
        });
        $("#btnRotate").click(function () {
            var url = "@Url.Action("Rotate", "ImageRotate", new { id = Model.Image.ImageId })";
            if("@Model.Path.Contains("Image")" == "True"){
                url += "?import=true";
            }
            $.ajax({
                type: 'GET',
                url: url,
                cache: false,
                contentType: "application/json; charset=utf-8",
                success: function (returndata) {
                    if ("Success" in returndata){
                        location.reload();
                    }else{
                        alert(returndata["Error"]);
                    }
                },
            });

        });
    });
    $(function () {
        $('.tooltip').tooltip({
            tooltipClass: ".tooltip",
            track: true,
            delay: 10,
            showURL: false,
            position: {
                my: "middle bottom",
                at: "middle top"
            }
        });
    });
    function DeleteConfirm(images) {
        if (confirm("Are you sure want to delete this image?"))
            return true;
        else
            return false;
    }
</script>

<div style="padding-left: 20px;">
    <h2>Image Detail</h2>
    <div class="col-6">
        <h4>
                <img src="@(Model.Path)Preview/@(ViewData.Model.Image.ImageDetailId).png"
                     alt="@(ViewData.Model.Image.ImageDetailId)" id="thumbnail" />
            <a class="inputButton" id="btnRotate">Rotate</a>
        </h4>
        @if (Model.Image.AdvertisingApproved)
        {
            <h4>
                <img src="@ContentHelper.ImagesRoot/tick.png" alt="Advertising Approved" class="displayed" />
            </h4>
        }

        <div class="imageno">@Model.Image.ImageDetail.Name.Trim()</div>
        <div class="imagesizes">
            <a href="/Image/Small/@(Model.Image.ImageId)" title="72dpi for internet" class="tooltip">Small |</a>
            <a href="/Image/Medium/@(Model.Image.ImageId)" title="150dpi for powerpoint" class="tooltip">Medium |</a>
            <a href="/Image/Download/@(Model.Image.ImageId)" title="300dpi for print" class="tooltip">Large</a>
        </div>

        <div style="float: left; font-size: small; width: 50px; margin-top: 10px; margin-left: 20px; clear:both">
            <a href="/Image/ImageDetail/@(Model.Image.ImageId)" class="imageinfo" id="@(Model.Image.ImageId)">
                <span style="float: right; font-size: small; width: 0px;">Info</span>
            </a>
        </div>
        <div style="float: right; margin-top: 5px">
            @if (Model.Image.InBasket())
            {
                <a href="/Basket/Remove/@(Model.Image.ImageId)?returnUrl=@(Request.RawUrl)" class="imageBasket">
                    <span style="font-size: small; margin-left: 20px;">Remove</span>
                </a>
            }
            else
            {
                <a href="/Basket/Add/@(Model.Image.ImageId)?returnUrl=@(Request.RawUrl)" class="imageBasket">
                    <span style="font-size: small; margin-left: 20px">Add to lightbox</span>
                </a>
            }
        </div>
    </div>
    <div class="col-6">
        @using (Html.BeginForm())
        {
            @Html.HiddenFor(model => model.Image.ImageId)
            @Html.HiddenFor(model => model.Page)
            <div id="select">
                <h4>
                    <span class="label">
                        @Html.LabelFor(model => model.Image.Category.CatalogId)
                    </span>
                    @Html.DropDownListFor(model => model.Image.Category.CatalogId, new SelectList(ViewBag.MoveCatalogs, "CatalogId", "Name", Model.Image.Category.CatalogId))
                </h4>
                <h4>
                    <span class="label">
                        @Html.LabelFor(model => model.Image.CategoryId)
                    </span>
                    @Html.DropDownListFor(model => model.Category.CategoryId, new SelectList(ViewBag.MoveCategories, "CategoryId", "Name", Model.Image.CategoryId), "Select category..")
                </h4>
               <h4>
                    <span class="label">
                        @Html.Label("Sub Category")
                    </span>
                    @Html.DropDownListFor(model => model.Image.SubCategoryId, new SelectList(ViewBag.MoveSubCategories, "SubCategoryId", "Name", Model.Image.SubCategoryId), "Select sub category..")
                </h4>
            </div>
            <h4>
                <span class="label">
                    @Html.Label("Name")
                </span>
                @if (User.IsInRole("PowerUser") || User.IsInRole("Administrator"))
                {
                    @Html.TextBoxFor(model => model.Image.ImageDetail.Name)
                }
                else
                {
                    @Model.Image.ImageDetail.Name
                }
            </h4>
            <h4>
                <span class="label">
                    @Html.Label("Description")
                </span>
                @if (User.IsInRole("PowerUser") || User.IsInRole("Administrator"))
                {
                    @Html.TextAreaFor(model => model.Image.ImageDetail.Description, 5, 50, null)
                }
                else
                {
                    @Html.TextAreaFor(model => model.Image.ImageDetail.Description, 5, 50, new { @readonly = true })
                }
            </h4>
            <h4>
                <span class="label">
                    @Html.Label("Size")
                </span>
                @Model.Image.FormattedSize
            </h4>
            <h4>
                <span class="label">
                    @Html.Label("Advertising Approved")
                </span>
                @if (User.IsInRole("PowerUser") || User.IsInRole("Administrator"))
                {
                    @Html.CheckBoxFor(model => model.Image.AdvertisingApproved, new { onclick = "$('#CopyImage').attr('checked','checked')" })
                }
                else
                {
                    @Model.Image.AdvertisingApproved
                }
            </h4>
            if (User.IsInRole("PowerUser") || User.IsInRole("Administrator"))
                {
                <div id="MoveDiv">
                    <h4>
                        <span class="label">
                            @Html.Label("Move Image?")
                        </span>
                        @Html.CheckBoxFor(model => model.MoveImage, new { @class="copy"})
                    </h4>
                    </div>
                    <div id="CopyDiv">
                        <h4>
                            <span class="label">
                                @Html.Label("Copy Image?")
                            </span>
                            @Html.CheckBoxFor(model => model.CopyImage)
                        </h4>
                    </div>
                    }
                    <div style="float: right; margin-right: 20px; margin-bottom: 20px;">
                        <input type="button" value="Go back" onclick="history.go(-1);" class="inputButton" />
                        @if (User.IsInRole("PowerUser") || User.IsInRole("Administrator"))
                {
                            <input type="submit" value="Update" class="inputButton" />
                            @Html.ActionLink("Delete", "Delete", "Image", new { id = Model.Image.ImageId, requestUrl = (Request.UrlReferrer == null) ? "" : Request.UrlReferrer.ToString() }, new {  @class = "DeleteButton" }) //onclick = "return DeleteConfirm()",
                }
                    </div>
                    }
                </div>
</div>

Foregate.Redrow/Views/Image/Import.cshtml
@model Foregate.Redrow.Models.CatalogListViewData
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@using Foregate.Redrow;
@using Foregate.Redrow.Helpers;
<script type="text/javascript">
    $(document).ready(function () {
        $('#Upload').scrollTop($('#Upload')[0].scrollHeight);
    });

    function updateMonitor(taskId, status) {
        $("#status").html(status);
    }

    $(function () {
        $("#load").click(function (e) {
            var url = '@Url.Action("Import", "Image")';
            var urlp = '@Url.Action("ImportProgress", "Image")';
            e.preventDefault();

            $.post(url, null, function (taskId) {

                // Init monitors
                $("#monitors").append($("<p id='status'/>"));
                updateMonitor(taskId, "Started");

                // Periodically update monitors
                var intervalId = setInterval(function () {
                    $.post(urlp, { id: taskId }, function (progress) {
                        if (progress == "") {
                            updateMonitor(taskId, "<b>Completed : </b>" + progress);
                            clearInterval(intervalId);
                            window.location.reload(true);
                        } else {
                            updateMonitor(taskId, progress);
                        }
                    });
                }, 100);
            });
        });
    });


</script>

@using (Html.BeginForm("Convert", "Image", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div id="monitors"></div>
    <h3>You are about to import the following files</h3>
    if (Model.files.Count() > 0)
    {
    <div>
        <ul>
            @foreach (var name in Model.files)
            { 
                <li>
                    @name
                </li> 
            }
        </ul>
        <div style="float: right; padding-bottom: 20px;">
            <button onclick="JavascriptFunction();" type="submit" id="load" class="inputButton">Upload</button>
        </div>
    </div>
    }
    else
    {
    @Html.Label("No files in the directory")
    }
    <div id="result">@Html.TextAreaFor(model => model.Upload, 14, 80, null)</div>
}

Foregate.Redrow/Views/Image/Integrity.cshtml
@{
    ViewBag.Title = "Integrity";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@using Foregate.Redrow;
@using Foregate.Redrow.Helpers;
@using Foregate.Redrow.Models;
<h2>Integrity</h2>
@using (Html.BeginForm())
{
    <div id="select">
        <h4>
            <span class="label">
                @Html.Label("Choose category")
            </span>
            @Html.DropDownList("Category", new SelectList(ViewBag.Categories, "CategoryId", "Name"))
        </h4>
        <input type="submit" value="Check" class="inputButton" />
    </div>
}